-- ==========================================
-- Amazon Price Tracker - Supabase SQL Schema
-- ==========================================

-- 1. Create Tables
CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asin TEXT UNIQUE NOT NULL,
    title TEXT,
    url TEXT NOT NULL
);

CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    price NUMERIC(10, 2),
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT fk_price_history_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);

CREATE TABLE tracking (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    target_price NUMERIC(10, 2) NOT NULL,
    last_notified_price NUMERIC(10, 2),
    CONSTRAINT fk_tracking_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE CASCADE
);

-- 2. Create Indexes
-- Index on ASIN for quick product lookups
CREATE INDEX idx_products_asin ON products(asin);
-- Indexes on foreign keys to optimize joins and cascading deletes
CREATE INDEX idx_price_history_product_id ON price_history(product_id);
CREATE INDEX idx_tracking_product_id ON tracking(product_id);

-- 3. Sample Insert Queries
/*
-- Run these to test the schema and query logic:

-- Insert a sample product
INSERT INTO products (asin, title, url) 
VALUES ('B08N5WRWNW', 'Apple MacBook Air M1', 'https://www.amazon.in/dp/B08N5WRWNW');

-- Insert a price history record
INSERT INTO price_history (product_id, price) 
VALUES (
    (SELECT id FROM products WHERE asin = 'B08N5WRWNW'), 
    75000.00
);

-- Setup tracking for the product
INSERT INTO tracking (product_id, target_price, last_notified_price) 
VALUES (
    (SELECT id FROM products WHERE asin = 'B08N5WRWNW'), 
    70000.00, 
    75000.00
);

-- View the inserted data:
SELECT p.asin, p.title, t.target_price, ph.price as current_price 
FROM products p
JOIN tracking t ON p.id = t.product_id
JOIN price_history ph ON p.id = ph.product_id
ORDER BY ph.timestamp DESC LIMIT 1;
*/
